version: '3'

services:
  bind9:
    container_name: dns-server
    image: ubuntu/bind9:9.18-23.04_edge
    environment:
      - BIND9_USER=root
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./config/:/etc/bind:rw
    network_mode: host
    restart: unless-stopped